package com.reimbursement.backend.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * Represents a professional certification available in the reimbursement system.
 * This entity stores information about various certifications that employees
 * can apply for reimbursement, including their category, recommended roles,
 * and current status.
 */
@Data
@Document(collection = "certifications")
public class Certification {

    /**
     * Unique identifier for the certification in the database.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The category or domain of the certification (e.g., "Technology", "Management", "Finance").
     * Helps in grouping and filtering certifications.
     */
    private String category;

    /**
     * The name or title of the certification (e.g., "AWS Certified Solutions Architect", "PMP").
     * This is the display name that users will see.
     */
    private String certification;

    /**
     * List of job roles that this certification is recommended for.
     * Helps in suggesting relevant certifications to employees based on their role.
     */
    private List<String> recommendedRoles;

    /**
     * Current status of the certification in the system.
     * Possible values might include "ACTIVE", "INACTIVE", "PENDING_REVIEW", etc.
     */
    private String status;
}
