package com.reimbursement.backend.security;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.security.Key;
import java.util.Date;

/**
 * Utility class for handling JSON Web Token (JWT) operations.
 *
 * <p>This class provides functionality to generate and validate JWT tokens for authentication
 * and authorization purposes in the Reimbursement Management System. It uses HMAC-SHA256
 * algorithm for signing tokens.</p>
 *
 * <p>JWT tokens generated by this utility contain the user's email as the subject claim
 * and include issued and expiration dates for token lifecycle management.</p>
 *
 * @author Reimbursement Management System
 * @version 1.0
 * @since 1.0
 */
@Component
public class JwtUtil {

    /**
     * JWT secret key loaded from application properties.
     * This secret is used to sign and verify JWT tokens.
     */
    @Value("${jwt.secret}")
    private String secret;

    /**
     * JWT expiration time in milliseconds loaded from application properties.
     * Defines how long generated tokens remain valid.
     */
    @Value("${jwt.expiration}")
    private long jwtExpiration;

    /**
     * Cryptographic key used for signing JWT tokens.
     * Initialized from the secret key using HMAC-SHA256 algorithm.
     */
    private Key key;

    /**
     * Initializes the JWT utility by creating the signing key from the secret.
     * This method is called automatically after bean construction.
     *
     * @PostConstruct annotation ensures this method runs after dependency injection.
     */
    @PostConstruct
    public void init() {
        this.key = Keys.hmacShaKeyFor(secret.getBytes());
    }

    /**
     * Generates a JWT token for the specified user email.
     *
     * <p>The generated token includes:
     * <ul>
     *   <li>Subject: User's email address</li>
     *   <li>Issued At: Current timestamp</li>
     *   <li>Expiration: Current time + configured expiration period</li>
     *   <li>Signature: HMAC-SHA256 using the secret key</li>
     * </ul>
     * </p>
     *
     * @param email The user's email address to be embedded in the token
     * @return A signed JWT token as a compact URL-safe string
     * @throws IllegalArgumentException if email is null or empty
     */
    public String generateToken(String email) {
        return Jwts.builder()
                .setSubject(email)
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + jwtExpiration))
                .signWith(key, SignatureAlgorithm.HS256)
                .compact();
    }

    /**
     *
     * @param token
     * @return extract token from email
     */
    public String extractEmail(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(key)
                .build()
                .parseClaimsJws(token)
                .getBody()
                .getSubject();
    }
}